"""add resolved_factor_id to suppliers

Revision ID: 4f2f34874e61
Revises: f637675b169d
Create Date: 2026-02-11 13:55:19.289193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2f34874e61'
down_revision: Union[str, Sequence[str], None] = 'f637675b169d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('resolved_factor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'emission_factors', ['resolved_factor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'resolved_factor_id')
    # ### end Alembic commands ###
