"""add parent to supplier

Revision ID: 62b705d32794
Revises: 0806eb95629e
Create Date: 2026-02-17 06:38:12.989262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b705d32794'
down_revision: Union[str, Sequence[str], None] = '0806eb95629e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'suppliers', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'parent_id')
    # ### end Alembic commands ###
