"""add emission calculation fields to spend_records

Revision ID: 772f3f179f19
Revises: 9889d1462284
Create Date: 2026-02-14 13:37:04.232649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772f3f179f19'
down_revision: Union[str, Sequence[str], None] = '9889d1462284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spend_records', sa.Column('calculated_co2e', sa.Numeric(), nullable=True))
    op.add_column('spend_records', sa.Column('factor_used_id', sa.UUID(), nullable=True))
    op.add_column('spend_records', sa.Column('calculated_at', sa.DateTime(), nullable=True))
    op.add_column('spend_records', sa.Column('calculation_method', sa.String(), nullable=True))
    op.create_foreign_key(None, 'spend_records', 'emission_factors', ['factor_used_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spend_records', type_='foreignkey')
    op.drop_column('spend_records', 'calculation_method')
    op.drop_column('spend_records', 'calculated_at')
    op.drop_column('spend_records', 'factor_used_id')
    op.drop_column('spend_records', 'calculated_co2e')
    # ### end Alembic commands ###
