"""add category_factor_mapping

Revision ID: 9578d17370e0
Revises: 29d3c43b0451
Create Date: 2026-02-11 09:22:09.764063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9578d17370e0'
down_revision: Union[str, Sequence[str], None] = '29d3c43b0451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emission_factors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_emission_factors_external_id'), 'emission_factors', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emission_factors_external_id'), table_name='emission_factors')
    op.alter_column('emission_factors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
