"""add factor_locked_at to suppliers

Revision ID: 9889d1462284
Revises: 4f2f34874e61
Create Date: 2026-02-11 14:24:02.854892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9889d1462284'
down_revision: Union[str, Sequence[str], None] = '4f2f34874e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('factor_locked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'factor_locked_at')
    # ### end Alembic commands ###
