"""add industry and carbon fields to suppliers

Revision ID: f637675b169d
Revises: 9578d17370e0
Create Date: 2026-02-11 13:30:17.872893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f637675b169d'
down_revision: Union[str, Sequence[str], None] = '9578d17370e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('industry_name', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('sbti_status', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('has_disclosure', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_suppliers_industry_name'), 'suppliers', ['industry_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_industry_name'), table_name='suppliers')
    op.drop_column('suppliers', 'has_disclosure')
    op.drop_column('suppliers', 'sbti_status')
    op.drop_column('suppliers', 'industry_name')
    # ### end Alembic commands ###
