"""add cascade delete

Revision ID: fa976131af79
Revises: 62b705d32794
Create Date: 2026-02-17 10:40:06.610032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa976131af79'
down_revision: Union[str, Sequence[str], None] = '62b705d32794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('emission_estimates_supplier_id_fkey'), 'emission_estimates', type_='foreignkey')
    op.create_foreign_key(None, 'emission_estimates', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('spend_records_supplier_id_fkey'), 'spend_records', type_='foreignkey')
    op.create_foreign_key(None, 'spend_records', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('supplier_disclosures_supplier_id_fkey'), 'supplier_disclosures', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_disclosures', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_disclosures', type_='foreignkey')
    op.create_foreign_key(op.f('supplier_disclosures_supplier_id_fkey'), 'supplier_disclosures', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'spend_records', type_='foreignkey')
    op.create_foreign_key(op.f('spend_records_supplier_id_fkey'), 'spend_records', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'emission_estimates', type_='foreignkey')
    op.create_foreign_key(op.f('emission_estimates_supplier_id_fkey'), 'emission_estimates', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
